version: "3.9"

services:
  kotlin-spring:
    container_name: kotlinardo
    build: backend
    ports:
      - 8080:8080
    depends_on:
      mysql: 
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/difficultApp?createDatabaseIfNotExist=true

  react:
    container_name: react
    build: frontend
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
 
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10000
      interval: 5s


    
